export { default as DashboardLayout } from './DashboardLayout';
export { default as Sidebar } from './Sidebar';
export { default as ScheduleTable } from './ScheduleTable';
export { default as AssignmentModal } from './AssignmentModal';
export { default as ProfesoresLayout } from './ProfesoresLayout';
export { default as ProfesoresModal } from './ProfesoresModal';
export { default as DisponibilidadModal } from './DisponibilidadModal';
export { default as AulasLayout } from './AulasLayout';
export { default as AulasModal } from './AulasModal';
