"""create initial database schema

Revision ID: 16238af16232
Revises: 
Create Date: 2026-02-11 15:17:26.005688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16238af16232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_aula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('NORMAL', 'LABORATORIO', 'COMPUTO', 'AUDITORIO', name='tipoaulaenum'), nullable=False),
    sa.Column('edificio', sa.String(length=50), nullable=True),
    sa.Column('piso', sa.Integer(), nullable=True),
    sa.Column('equipamiento', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aulas_activo'), 'aulas', ['activo'], unique=False)
    op.create_index(op.f('ix_aulas_codigo_aula'), 'aulas', ['codigo_aula'], unique=True)
    op.create_index(op.f('ix_aulas_id'), 'aulas', ['id'], unique=False)
    op.create_index(op.f('ix_aulas_tipo'), 'aulas', ['tipo'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_grupo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('carrera', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('turno', sa.Enum('MATUTINO', 'VESPERTINO', 'NOCTURNO', name='turnoenum'), nullable=False),
    sa.Column('num_estudiantes', sa.Integer(), nullable=False),
    sa.Column('ciclo_escolar', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_ciclo_escolar'), 'grupos', ['ciclo_escolar'], unique=False)
    op.create_index(op.f('ix_grupos_codigo_grupo'), 'grupos', ['codigo_grupo'], unique=True)
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_materia', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('horas_semana', sa.Integer(), nullable=False),
    sa.Column('requiere_laboratorio', sa.Boolean(), nullable=False),
    sa.Column('tipo_aula_requerida', sa.Enum('NORMAL', 'LABORATORIO', 'COMPUTO', 'AUDITORIO', name='tipoaulaenum'), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materias_activo'), 'materias', ['activo'], unique=False)
    op.create_index(op.f('ix_materias_codigo_materia'), 'materias', ['codigo_materia'], unique=True)
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('codigo_docente', sa.String(length=20), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('horas_maximas_semana', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docentes_codigo_docente'), 'docentes', ['codigo_docente'], unique=True)
    op.create_index(op.f('ix_docentes_id'), 'docentes', ['id'], unique=False)
    op.create_index(op.f('ix_docentes_user_id'), 'docentes', ['user_id'], unique=True)
    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_escolar', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'materia_id', 'ciclo_escolar', name='unique_asignacion_grupo_materia_ciclo')
    )
    op.create_index(op.f('ix_asignaciones_ciclo_escolar'), 'asignaciones', ['ciclo_escolar'], unique=False)
    op.create_index(op.f('ix_asignaciones_docente_id'), 'asignaciones', ['docente_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_grupo_id'), 'asignaciones', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_id'), 'asignaciones', ['id'], unique=False)
    op.create_index(op.f('ix_asignaciones_materia_id'), 'asignaciones', ['materia_id'], unique=False)
    op.create_table('disponibilidad_docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', name='diasemanaenum'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('hora_fin > hora_inicio', name='check_hora_fin_mayor'),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docente_id', 'dia_semana', 'hora_inicio', 'hora_fin', name='unique_disponibilidad')
    )
    op.create_index(op.f('ix_disponibilidad_docente_docente_id'), 'disponibilidad_docente', ['docente_id'], unique=False)
    op.create_index(op.f('ix_disponibilidad_docente_id'), 'disponibilidad_docente', ['id'], unique=False)
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', name='diasemanaenum'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('tipo_sesion', sa.Enum('TEORICA', 'PRACTICA', 'LABORATORIO', name='tiposesionenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('hora_fin > hora_inicio', name='check_horario_hora_fin_mayor'),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_asignacion_id'), 'horarios', ['asignacion_id'], unique=False)
    op.create_index(op.f('ix_horarios_aula_id'), 'horarios', ['aula_id'], unique=False)
    op.create_index(op.f('ix_horarios_id'), 'horarios', ['id'], unique=False)
    op.create_table('conflictos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_conflicto', sa.Enum('DOCENTE_OCUPADO', 'AULA_OCUPADA', 'GRUPO_OCUPADO', 'CAPACIDAD_EXCEDIDA', name='tipoconflictoenum'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflictos_horario_id'), 'conflictos', ['horario_id'], unique=False)
    op.create_index(op.f('ix_conflictos_id'), 'conflictos', ['id'], unique=False)
    op.create_index(op.f('ix_conflictos_resuelto'), 'conflictos', ['resuelto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conflictos_resuelto'), table_name='conflictos')
    op.drop_index(op.f('ix_conflictos_id'), table_name='conflictos')
    op.drop_index(op.f('ix_conflictos_horario_id'), table_name='conflictos')
    op.drop_table('conflictos')
    op.drop_index(op.f('ix_horarios_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_aula_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_asignacion_id'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_disponibilidad_docente_id'), table_name='disponibilidad_docente')
    op.drop_index(op.f('ix_disponibilidad_docente_docente_id'), table_name='disponibilidad_docente')
    op.drop_table('disponibilidad_docente')
    op.drop_index(op.f('ix_asignaciones_materia_id'), table_name='asignaciones')
    op.drop_index(op.f('ix_asignaciones_id'), table_name='asignaciones')
    op.drop_index(op.f('ix_asignaciones_grupo_id'), table_name='asignaciones')
    op.drop_index(op.f('ix_asignaciones_docente_id'), table_name='asignaciones')
    op.drop_index(op.f('ix_asignaciones_ciclo_escolar'), table_name='asignaciones')
    op.drop_table('asignaciones')
    op.drop_index(op.f('ix_docentes_user_id'), table_name='docentes')
    op.drop_index(op.f('ix_docentes_id'), table_name='docentes')
    op.drop_index(op.f('ix_docentes_codigo_docente'), table_name='docentes')
    op.drop_table('docentes')
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_index(op.f('ix_materias_codigo_materia'), table_name='materias')
    op.drop_index(op.f('ix_materias_activo'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_codigo_grupo'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_ciclo_escolar'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_aulas_tipo'), table_name='aulas')
    op.drop_index(op.f('ix_aulas_id'), table_name='aulas')
    op.drop_index(op.f('ix_aulas_codigo_aula'), table_name='aulas')
    op.drop_index(op.f('ix_aulas_activo'), table_name='aulas')
    op.drop_table('aulas')
    # ### end Alembic commands ###
