"""Create horario_versiones table

Revision ID: horario_versions_001
Revises: 16238af16232
Create Date: 2026-02-23 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'horario_versions_001'
down_revision = '16238af16232'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario_versiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('version_numero', sa.Integer(), nullable=False),
    sa.Column('ciclo_escolar', sa.String(length=20), nullable=False),
    sa.Column('estado_anterior', sa.JSON(), nullable=True),
    sa.Column('estado_nuevo', sa.JSON(), nullable=False),
    sa.Column('tipo_cambio', sa.String(length=50), nullable=False),
    sa.Column('descripcion_cambio', sa.String(length=500), nullable=False),
    sa.Column('razon_cambio', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('version_numero > 0', name='check_version_numero_positivo'),
    sa.CheckConstraint("tipo_cambio IN ('creacion', 'modificacion', 'eliminacion', 'rollback')", name='check_tipo_cambio_valido'),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ciclo_escolar', 'horario_versiones', ['ciclo_escolar'])
    op.create_index('idx_created_at', 'horario_versiones', ['created_at'])
    op.create_index('idx_horario_id', 'horario_versiones', ['horario_id'])
    op.create_index('idx_horario_version', 'horario_versiones', ['horario_id', 'version_numero'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_horario_version', table_name='horario_versiones')
    op.drop_index('idx_created_at', table_name='horario_versiones')
    op.drop_index('idx_ciclo_escolar', table_name='horario_versiones')
    op.drop_index('idx_horario_id', table_name='horario_versiones')
    op.drop_table('horario_versiones')
    # ### end Alembic commands ###
